const quizData = [
  {
    id: 1,
    question: "('b' + 'a' + + 'a' + 'a').toLowerCase()",
    a: "bananaa",
    b: "baaa",
    c: "banana",
    d: "ananas",
    correct: "d",
  },
  {
    id: 2,
    question: "Quyidagilardan qaysi biri JavaScript-da false qiymat.",
    a: "0",
    b: "“false”",
    c: "undefined",
    d: "Yuqoridagilarning barchasi",
    correct: "d",
  },
  {
    id: 3,
    question:
      "JavaScript-da document.getElementById() method idan maqsad nima?",
    a: "Kiritilgan elementning qiymatini olish uchun",
    b: "Sahifaning sarlavhasini o'zgartirish uchun",
    c: "Elementni ID bo‘yicha olish uchun",
    d: "Yangi HTML elementini qo'shish uchun",
    correct: "c",
  },
  {
    id: 4,
    question: "Qaysi array metodi massivning elementlar sonini qaytaradi?",
    a: "length",
    b: "pop",
    c: "push",
    d: "shift",
    correct: "a",
  },
  {
    id: 5,
    question: "true || false || true",
    a: "true",
    b: "false",
    c: "null",
    d: "NaN",
    correct: "a",
  },

  {
    id: 6,
    question: "JavaScript-da JSON.parse() funksiyasining maqsadi nima?",
    a: "json formatidagi malumotni Obyektga almashtiradi.",
    b: "O‘zgaruvchining qiymatini o‘zgartirish uchun",
    c: "Massivga yangi element qo‘shish uchun",
    d: "Obyektni   JSON dagi  malumotga almashtiradi.",
    correct: "a",
  },
  {
    id: 7,
    question:
      "JavaScript-da bir nechta satrlarni qamrab oluvchi izoh qo'shishning to'g'ri usuli qanday?",
    a: "/* Bu sharh */",
    b: "// Bu sharh",
    c: "<!– Bu izoh –>",
    d: "# Bu izoh #",
    correct: "togrijavob",
  },

  {
    id: 8,
    question: "JavaScript-da Array.isArray() usulining maqsadi nima?",
    a: "Massivdan birinchi elementni olib tashlash uchun",
    b: "Massivga element qo‘shish uchun",
    c: "O‘zgaruvchining massiv ekanligini tekshirish uchun",
    d: "Obyektni massivga aylantirish uchun",
    correct: "c",
  },
  {
    id: 9,
    question:
      "Ikki yoki undan ortiq satrlarni birlashtirish uchun qaysi JavaScript operatoridan foydalaniladi?",
    a: "+",
    b: "add",
    c: "...",
    d: "&",
    correct: "a",
  },
  {
    id: 11,
    question: "let raqam = 3; raqam === '3' ?",
    a: "true",
    b: "false",
    c: "-3",
    d: "3",
    correct: "b",
  },
  {
    id: 12,
    question: "6!=6",
    a: "true",
    b: "false",
    c: "6",
    d: "5",
    correct: "b",
  },
  {
    id: 13,
    question: "' ' - 1",
    a: "1",
    b: "-1",
    c: "NAN",
    d: "Infinify",
    correct: "b",
  },
  {
    id: 14,
    question: "0.2+0.1 === 0.3",
    a: "true",
    b: "false",
    c: "NAN",
    d: "null",
    correct: "b",
  },
  {
    id: 15,
    question: "[] == []",
    a: "true",
    b: "false",
    c: "NAN",
    d: "null",
    correct: "b",
  },
  {
    id: 16,
    question: "true == true",
    a: "true",
    b: "false",
    c: "NAN",
    d: "null",
    correct: "a",
  },
  {
    id: 17,
    question: "true == 1",
    a: "true",
    b: "false",
    c: "NAN",
    d: "null",
    correct: "a",
  },
  {
    id: 18,
    question: "true == 2",
    a: "true",
    b: "false",
    c: "NAN",
    d: "null",
    correct: "b",
  },
  {
    id: 19,
    question: "{} == {}",
    a: "true",
    b: "false",
    c: "NAN",
    d: "null",
    correct: "b",
  },
  {
    id: 20,
    question: "false == '0'",
    a: "true",
    b: "false",
    c: "NAN",
    d: "null",
    correct: "a",
  },
  {
    id: 21,
    question: "3 > 2 > 1",
    a: "true",
    b: "false",
    c: "NAN",
    d: "null",
    correct: "a",
  },
  {
    id: 22,
    question: "typeof typeof 1",
    a: "number",
    b: "false",
    c: "1",
    d: "string",
    correct: "d",
  },
  {
    id: 23,
    question: `"This is a string." instanceof String`,
    a: "true",
    b: "false",
    c: "NAN",
    d: "error",
    correct: "b",
  },
  {
    id: 24,
    question: "[33, 2, 8].sort()[1]",
    a: "2",
    b: "8",
    c: "33",
    d: "null",
    correct: "c",
  },
  {
    id: 25,
    question: "018 - 015",
    a: "NAN",
    b: "3",
    c: "5",
    d: "23",
    correct: "c",
  },
  {
    id: 26,
    question: "(true == []) + (true == ![])",
    a: "true",
    b: "false",
    c: "0",
    d: "1",
    correct: "c",
  },
  {
    id: 27,
    question: "eval('10*10+5')",
    a: "10*10+5",
    b: "1005",
    c: "105",
    d: "null",
    correct: "c",
  },
  {
    id: 28,
    question: "!!' '",
    a: "true",
    b: "false",
    c: "NAN",
    d: "null",
    correct: "b",
  },
  {
    id: 29,
    question: "true == 2",
    a: "true",
    b: "false",
    c: "NAN",
    d: "null",
    correct: "b",
  },
  {
    id: 30,
    question: "false || {} || null",
    a: "true",
    b: "false",
    c: "{}",
    d: "null",
    correct: "c",
  },
  {
    id: 31,
    question: "23 || 45",
    a: "true",
    b: "false",
    c: "45",
    d: "23",
    correct: "d",
  },
  {
    id: 32,
    question: "[] + []",
    a: "''",
    b: "2",
    c: "0",
    d: "undefined",
    correct: "a",
  },
  {
    id: 33,
    question: "0 && 12",
    a: "0",
    b: "12",
    c: "true",
    d: "false",
    correct: "a",
  },
  {
    id: 34,
    question: "undefined * 23",
    a: "true",
    b: "false",
    c: "0",
    d: "NaN",
    correct: "d",
  },
  {
    id: 35,
    question: "[] || 0 || true",
    a: "true",
    b: "false",
    c: "[]",
    d: "0",
    correct: "c",
  },
];
