const quizData = [
  {
    question:
      "JavaScript-da o'zgaruvchini e'lon qilishning to'g'ri yo'li qanday?",
    a: "let myVar = 10;",
    b: "var myVar = 10;",
    c: "const myVar = 10;",
    d: "Yuqoridagilarning barchasi",
    correct: "d",
  },
  {
    question: "Quyidagilardan qaysi biri JavaScript-da false qiymat.",
    a: "0",
    b: "“false”",
    c: "undefined",
    d: "Yuqoridagilarning barchasi",
    correct: "d",
  },
  {
    question:
      "JavaScript-da document.getElementById() method idan maqsad nima?",
    a: "Kiritilgan elementning qiymatini olish uchun",
    b: "Sahifaning sarlavhasini o'zgartirish uchun",
    c: "Elementni ID bo‘yicha olish uchun",
    d: "Yangi HTML elementini qo'shish uchun",
    correct: "c",
  },
  {
    question: "Qaysi array metodi massivning elementlar sonini qaytaradi?",
    a: "length",
    b: "pop",
    c: "push",
    d: "shift",
    correct: "a",
  },
  {
    question: "true || false || true",
    a: "true",
    b: "false",
    c: "null",
    d: "NaN",
    correct: "a",
  },

  {
    question: "JavaScript-da JSON.parse() funksiyasining maqsadi nima?",
    a: "json formatidagi malumotni Obyektga almashtiradi.",
    b: "O‘zgaruvchining qiymatini o‘zgartirish uchun",
    c: "Massivga yangi element qo‘shish uchun",
    d: "Obyektni   JSON dagi  malumotga almashtiradi.",
    correct: "a",
  },
  {
    question:
      "JavaScript-da bir nechta satrlarni qamrab oluvchi izoh qo'shishning to'g'ri usuli qanday?",
    a: "/* Bu sharh */",
    b: "// Bu sharh",
    c: "<!– Bu izoh –>",
    d: "# Bu izoh #",
    correct: "togrijavob",
  },

  {
    question: "JavaScript-da Array.isArray() usulining maqsadi nima?",
    a: "Massivdan birinchi elementni olib tashlash uchun",
    b: "Massivga element qo‘shish uchun",
    c: "O‘zgaruvchining massiv ekanligini tekshirish uchun",
    d: "Obyektni massivga aylantirish uchun",
    correct: "c",
  },
  {
    question:
      "Ikki yoki undan ortiq satrlarni birlashtirish uchun qaysi JavaScript operatoridan foydalaniladi?",
    a: "+",
    b: "add",
    c: "...",
    d: "&",
    correct: "a",
  },
  {
    question: "JavaScript-da try…catch bayonotining maqsadi nima?",
    a: "Yangi funksiyani aniqlash uchun",
    b: "O‘zgaruvchini e’lon qilish uchun",
    c: "Istisnolar va xatolarni boshqarish uchun",
    d: "Halqa yaratish uchun",
    correct: "togrijavob",
  },
  {
    question: "let raqam = 3; raqam === '3' ?",
    a: "true",
    b: "false",
    c: "-3",
    d: "3",
    correct: "b",
  },

  {
    question: "6!=6",
    a: "true",
    b: "false",
    c: "6",
    d: "5",
    correct: "b",
  },

  {
    question: "' ' - 1",
    a: "1",
    b: "-1",
    c: "NAN",
    d: "Infinify",
    correct: "b",
  },
  {
    question: "0.2+0.1 === 0.3",
    a: "true",
    b: "false",
    c: "NAN",
    d: "null",
    correct: "b",
  },
  {
    question: "[] == []",
    a: "true",
    b: "false",
    c: "NAN",
    d: "null",
    correct: "b",
  },
  {
    question: "{} == {}",
    a: "true",
    b: "false",
    c: "NAN",
    d: "null",
    correct: "b",
  },
  {
    question: "true == true",
    a: "true",
    b: "false",
    c: "NAN",
    d: "null",
    correct: "a",
  },
  {
    question: "true == 1",
    a: "true",
    b: "false",
    c: "NAN",
    d: "null",
    correct: "a",
  },
  {
    question: "true == 2",
    a: "true",
    b: "false",
    c: "NAN",
    d: "null",
    correct: "b",
  },
];
